# Generated by Django 4.1 on 2022-08-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='meals',
            new_name='item',
        ),
    ]
