# Generated by Django 4.1 on 2022-08-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_meals_item_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item',
            field=models.CharField(choices=[('PT', 'Potion'), ('SP', 'Super Potion'), ('HP', 'Hyper Potion'), ('RC', 'Rare Candy'), ('RV', 'Revive')], max_length=2, verbose_name='Item Given'),
        ),
    ]
