# Generated by Django 4.1 on 2022-08-11 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_move_alter_item_options_pokemon_move_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='move_list',
            new_name='moves',
        ),
    ]
